### ISSUE TITLE
Bot don't work on pancakeswap

### ISSUE THREAD

**Issue by 12ligne** [Amarjeet-L/defi-auto-harvester#1]
When I replace all contract adresses, rpc, chain ID, abi, I obtain an opcode error. Any idea ?

**Comment by 12ligne** [comment]
Sorry, to reopened this issue but on bsc mainnet, price log displays "infinity" and I doesn’t find the error. If you have any idea…

**Comment by Amarjeet-L** [comment]
The bot is only for Polygon network
